### ISSUE TITLE
Keyword CONTROLLER_ADDRESSES is not identified by the lib

### ISSUE THREAD

**Issue by sabarinathbs** [ihedvall/a2llib#6]
There is an issue with one of the keyword CONTROLLER_ADDRESSES in a2l file. While parsing, I am getting a syntax error for this keyword. The error shows "syntax error near /begin  CONTROLLER_ADDRESSES"

**Comment by sabarinathbs** [comment]
[sample_a2l.txt](https://github.com/user-attachments/files/16201204/sample_a2l.txt)

**Comment by ihedvall** [comment]
The supplied A2L files have some issues as there is a /end MODULE tag but no matching /begin MODULE tag. Is it OK to add this tag to the controller_ADDRESSES files?

**Comment by sabarinathbs** [comment]
> The supplied A2L files have some issues as there is a /end MODULE tag but no matching /begin MODULE tag. Is it OK to add this tag to the controller_ADDRESSES files?

Yes it is ok

**Comment by ihedvall** [comment]
I have fixed the parser but I had to add an underscore to the BYTE ORDER tag (BYTE_ORDER). Just checking if it's more changes needed? I have not checked in changes yet.

**Comment by ihedvall** [comment]
I have added the CONTROLLER_ADDRESSES tag support. Please test on your A2L files

**Comment by sabarinathbs** [comment]
Hi @ihedvall , tested the fix. Its working fine
